### PR TITLE
Add closing dropdown on outside click

### PR DESCRIPTION
**Pull request by vladpopovv**
**Changes**
- Add click handler to detect outside click
- Add closing  dropdown on outside click
- Update readme

### CODE REVIEW

**Comment by vladpopovv** [comment]
@bedmonds could you please take a look at this pull request?

**Comment by vladpopovvbb** [comment]
Hi @mikerodham, I have one improvement for your dropdown. Could you please take a look at these changes?

**Comment by vladpopovv** [comment]
Hi @mikerodham, I have one improvement for your dropdown. Could you please take a look at these changes?

**Comment by mikerodham** [comment]
Apologies for the delay @vladpopovv I was finding some time to test it and check if it's required. It all looks good to me, so I'll get that updated on npm for you. Thanks for contributing!

**Pull request merged**
